### PR TITLE
Backport of #95 - rspec rails clash

### PR DESCRIPTION
**Pull request by bk-one**

### CODE REVIEW

**Comment by bk-one** [comment]
As this is driving me nuts currently, I've backported #95 for the current 2.x branch. Not sure if this was intentionally left for 3.x, but here it is.

**Comment by Mange** [comment]
Any update on this?

**Comment by Mange** [comment]
I handled this by monkey patching my codebase as such:

```ruby
# Monkey patch. See https://github.com/philostler/rspec-sidekiq/pull/108
if Gem::Dependency.new('rspec-sidekiq', '< 3.0.0').matching_specs.any?
  module RSpec
    module Sidekiq
      module Matchers
        if Gem::Dependency.new('rspec-rails', '>= 3.4.0').matching_specs.max_by(&:version)
          alias have_enqueued_sidekiq_job have_enqueued_job
        end
      end
    end
  end
end
```

I removed the `warn` since it was writing out the deprecation warnings at all times, even when the old matcher isn't used.

**Comment by adamgotterer** [comment]
Any progress on this?

**Comment by baburdick** [comment]
👍 Also needed here.

**Comment by packrat386** [comment]
Now that we've released 3.0 is this change still needed?

**Comment by baburdick** [comment]
There may be others who are unable to upgrade to v3 at this time. Might make sense to merge/tag/release it to provide them relief until they can upgrade.

**Comment by bk-one** [comment]
What @baburdick said .. we haven't upgraded yet. I can let you know once we have.

**Comment by Mange** [comment]
> Now that we've released 3.0 is this change still needed?

We upgraded to 3.0 recently; I could remove my monkey patch and everything is working like before.

---

I won't comment on whether or not a patch-level release should be released in the 2.x series. That's up to the maintainer and those that have issues with it.

**Comment by baburdick** [comment]
Also upgraded some time ago. Just now stumbling across my now ancient monkey patch, removing it, and seeing tests blithely succeed. All good here.

**Pull request closed without merging**
